### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by paaljoachim** [KZeni/Disable-WordPress-Theme-and-Plugin-Auto-Update-Emails#1]
Hey

Check out this code from one of the Core developers.
https://gist.github.com/afragen/e2f40ed2e71e590a127e8adc1db05948

**Comment by KZeni** [comment]
Ah, I take it you want it to still notify if/when a plugin failed to update. That's definitely something to consider.

I wonder if that should simply be the new functionality or have that be a setting where people that don't want any plugin emails can still have it act that way for a greater level of control. I like the simplicity of just enabling this plugin while it really would be most common that people would still want to know if a plugin update failed, but I can also see some cases where a hosting setup might have plugins not able to update themselves for some reason where one would want to disable these emails completely while it'd then need to add a setting to adjust this behavior. 🤔

Let me know what your preference would be so I can take that into consideration.

*Edit: I've gone ahead and made the default have it not block failed update notifications (mostly seamless with existing users where failed updates should be rare while useful for most people to know if/when an issue occurred during updates [successful updates still not sending the notification just by having the plugin enabled]) while there's now a setting on Settings => General for "Also disable failed update email notifications" which will have it return to the previous behavior of blocking all plugin & theme update email notifications.

**Comment by KZeni** [comment]
@paaljoachim Would you be willing to try version 1.1 where this has been patched in?

It's available here on GitHub (https://github.com/KZeni/Disable-WordPress-Theme-and-Plugin-Auto-Update-Emails) with it rolling out to WP.org once it's showing as working properly.

Confirmation that the v1.1 update is working for others will help speed up this being released on WP.org.

**Comment by KZeni** [comment]
@paaljoachim Actually going to consider this version 2.0 since it's adding a major feature. Also added some links to the plugin details on the plugin page in the site admin which can be helpful (one of which is a link to the specific settings section so people can find it quickly & easily with it being on the main general settings page [it just being a single checkbox toggle didn't really warrant it having a full settings page.])

GitHub has been updated to this latest release while further testing is to be done before pushing it out to WP.org.

I've bundled this for easy installing/updating the pre-release version here: https://f.kzeni.com/disable-theme-and-plugin-auto-update-emails-2-0-pre-release.zip

**Comment by paaljoachim** [comment]
Hi @KZeni Kurt

I went to one of my sites and deactivated the code snippet (code shared in the initial comment) and instead activated your plugin.

Regarding:
![Screenshot 2022-08-28 at 10 22 19](https://user-images.githubusercontent.com/5323259/187064848-8e7056d9-0b72-4fe6-935c-563462666ae0.jpg)

and the setting:
![Screenshot 2022-08-28 at 10 23 14](https://user-images.githubusercontent.com/5323259/187064860-cc6ed2ff-3ccc-4cb3-a471-3678f57e069a.jpg)



There could actually be two settings:
- Disable success e-mails. (Could by default already be clicked because the plugin has been activated.)
- Disable all e-mails. (User would need to activate to use this setting.)

**Comment by KZeni** [comment]
@paaljoachim Yes, there could be two settings, but what would be the point of having "Disable Success E-mails" added as a setting? That's effectively the same thing as just enabling/disabling the plugin itself (as mentioned in the new setting's description so those looking for a setting to do that know to simply deactivate the plugin to get that desired effect.)

Why would you have a setting to effectively deactivate the plugin from doing anything when there's already the option to just enable/disable the plugin?

Also, there really wouldn't ever be a case where failed updates emails would want/need to be blocked while successful update emails wouldn't so splitting those out as separate settings doesn't really make sense there, either.

That seems like it would add unnecessary complexity & bloat in order to provide something that's already available via a WordPress standard (just deactivate the plugin if you don't want it to do anything.)

Also, adding that setting would allow people to do a bad practice where they have the plugin enabled so it's loading the plugin's code & everything just to have it do nothing when it should simply just not have the plugin enabled (per the plugin doing what it says it will do when enabled) so their site is kept more lightweight (while the plugin is very lightweight, it's still enabling people to make things worse-off [even if it's nearly imperceivable] when there's a better way of doing what they want.)

Even if this is for a WordPress Network/Multi-Site setup consideration... it doesn't really make sense since theme & plugin updates are affecting the network install as a whole & isn't really site-specific (unlike something where they might have the plugin network activated & only want the behavior to apply to a subset of sites on the network... the theme & plugin updates are affecting all sites on the network & them not wanting those success emails are highly likely to be the case for all sites on the network.) Meanwhile, they could just not network activate the plugin & just activate it for the individual site(s) to accommodate this use case (again, there already is a better way to do this without needing a separate setting that then just adds complexity & other downsides.)

I did edit the setting field's description just now to convey all that needs to be done to allow successful update emails through is to deactivate the plugin (so they might look for that setting there and see that they should just deactivate the plugin for what they want.)

Is there some aspect / use case / etc. I'm missing here where adding that as an option would make sense?

**Comment by KZeni** [comment]
@paaljoachim Let me know if you have any follow-up / discussion regarding things (feel free to open a new issue as this did complete the initial request of this issue of making it so failed updates can still have their email notification go through.)

https://wordpress.org/plugins/disable-theme-and-plugin-auto-update-emails/ has been updated to have version 2.0 available for download (tested on multiple PHP & WordPress versions without issue and it has what the pre-release had just with a minor text adjustment to clarify how activating/deactivating the plugin serves as the setting for preventing/allowing emails upon successful theme & plugin updates.)

**Comment by paaljoachim** [comment]
Hi @KZeni 

> Why would you have a setting to effectively deactivate the plugin from doing anything when there's already the option to just enable/disable the plugin?

The reason why I suggested having two checkboxes was to make it really clear that the plugin can do two things.
Of course one can have a prechecked radio box letting the user know that when activating the plugin that emails are disabled.
Or as you say when activating the plugin will automatically disable the auto update e-mails.

> I did edit the setting field's description just now to convey all that needs to be done to allow successful update emails through is to deactivate the plugin (so they might look for that setting there and see that they should just deactivate the plugin for what they want.)

Great!

**Comment by KZeni** [comment]
@paaljoachim Okay, I'm going to be releasing 2.0.1 where it, more importantly, avoids a potential PHP error in certain circumstances while also having it now show "Disable successful update email notifications" alongside "Disable failed update email notifications" as settings on the Settings => General page. Now, the checkbox for disabling successful update alert is always checked with that not actually being a setting that does anything while the description then says how simply activating/deactivating the plugin acts as the better approach to having that be a setting (per that setting effectively making the plugin not doing anything per there not being a use case where one would want failed plugin updates to not notify while successful ones do [people want to know if something went wrong more than if stuff's simply working as intended.])
